### ISSUE TITLE
Please help me understand how i can read from and write to different pages of 0x51

### ISSUE THREAD

**Issue by MykeHalk** [ubihazard/ddr5-spd-recovery#1]
Im having an issue where im not able to use your spdwrite.py script because most of my RSWP blocks are write protected. 2 of them are not tho and because of a the program OpenRGB it caused a few bytes to change im assuming, causing the vendor RGB controller firmware not to work anymore for one of my DIMM's. my other dimm is fine and i used a hex editor to compare which bits are different, but im having a hard time changing the bits because im only knowledgable enough to read only the first page of bytes using i2cget

Can you please help me get this figured out? Its literally like 3 bytes that need changing im assuming in the non write protected blocks.

I just need help figuring out how to properly use i2cget and i2cset

**Comment by ubihazard** [comment]
You are right. In my original upload of `spdwrite.py` it didn't take into account already protected modules and it could only write over entire contents of SPD. It was a quick solution for my problem with TEAMGROUP T-Creates at the time. I should have addressed this sooner because such functionality is very much needed.

I've just updated `spdwrite.py` with both abilities: it is now possible to do partial flashes (changing only three bytes, like you said) and the tool now skips over write-protected portions of EEPROM automatically (you will see it in the output log). Search for "Flashing the ROM is straightforward" on the [repo page](https://github.com/ubihazard/ddr5-spd-recovery) for updated instructions.

Feel free to test it if you still have your problem with RGB and reopen this issue in case if it still doesn't work.

And sorry for late reply. Barely have any time to be on GitHub lately.
